name: CI/CD Pipeline

on:
  push:
    branches: [ main, ci/cd_changes ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4 to remove Node.js warning

      - name: Create required directories
        run: |
          mkdir -p mlruns
          mkdir -p data
          chmod -R 777 mlruns data

      - name: Start Services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run Pytest inside API Container
        run: |
          docker compose exec -T api pytest tests/ --maxfail=3 --disable-warnings -q
        env:
          PYTHONPATH: /app

      - name: Stop and Cleanup Containers
        if: always()
        run: docker compose down